id: 03-docker
rocnik: bonus
nazev: Docker
modul: nastroje-vyvoje
hodiny: 0
obtiznost: zacatecnik
prerekvizity: [02-git-a-github]
kompetence: [k3-strukturovane-programy]
svp: [vývojové prostředí]
tagy: [docker, kontejnery, ide, bonus]
migrovano_z: []
