id: 01-git-a-github
rocnik: bonus
nazev: Git a GitHub
modul: nastroje-vyvoje
hodiny: 0
obtiznost: zacatecnik
prerekvizity: [27-funkce-pokrocile]
kompetence: [k3-strukturovane-programy]
svp: [vývojové prostředí]
tagy: [git, github, ide, bonus]
migrovano_z: []
