id: 03-orm
rocnik: bonus
nazev: ORM
modul: orm
hodiny: 0
obtiznost: stredni
prerekvizity: [20-databaze-procviceni]
kompetence: [k4-formulare-skript]
svp: [propojení skriptu a databáze, skriptovací jazyk]
tagy: [flask, orm, sqlalchemy, bonus]
migrovano_z: []
